# Generated by Django 4.1.7 on 2023-02-24 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMPUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='faculté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculténom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NATIONALITE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NATIONNOM', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PROGRAMME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROGRAMMENOM', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UNIVERSITE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIVERSITENOM', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('NOM', models.CharField(default='', max_length=50)),
                ('PRENOM', models.CharField(default='', max_length=50)),
                ('POSTNOM', models.CharField(default='', max_length=50)),
                ('EMAIL', models.EmailField(max_length=254, verbose_name='Email...')),
                ('NOM_DE_LA_PERE', models.CharField(max_length=30, verbose_name='NOM DU PARENT ...')),
                ('NOM_DE_LA_MERE', models.CharField(max_length=40, verbose_name='NOM DU PARENT...')),
                ('PHOTO', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('DIPLOMES', models.FileField(upload_to='books/secondary certificate/')),
                ('NIVEAU_EN_ANGLAIS', models.FileField(upload_to='books/competencelangue/')),
                ('COPIE_DU_PASSPORT', models.FileField(upload_to='books/passport/')),
                ('DATE_DE_NAISSANCE', models.DateField(default='2000-01-01')),
                ('LIEU_DE_NAISSANCE', models.CharField(max_length=50, verbose_name='LIEU ...')),
                ('NUMERO_DE_TELEPHONE', models.CharField(blank=True, max_length=20, null=True)),
                ('FACULTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculté')),
                ('LOGEMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.campus')),
                ('NATIONALITE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nationalite')),
                ('PROGRAMME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.programme')),
                ('UNIVERSITE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.universite')),
            ],
        ),
    ]
