# Generated by Django 4.1.7 on 2023-02-26 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_campus_faculté_nationalite_programme_universite_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='NOM_DE_LA_PERE',
            new_name='NOM_DU_PERE',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='NUMERO_DE_TELEPHONE',
            new_name='NUMERO_DE_TEL',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='campus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
