# Generated by Django 4.1.7 on 2023-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_nom_de_la_pere_post_nom_du_pere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EMAIL',
            field=models.EmailField(max_length=254, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='post',
            name='NOM_DE_LA_MERE',
            field=models.CharField(max_length=40, verbose_name='NOM DU PARENT '),
        ),
        migrations.AlterField(
            model_name='post',
            name='NOM_DU_PERE',
            field=models.CharField(max_length=30, verbose_name='NOM DU PARENT '),
        ),
    ]
