# Generated by Django 4.1.7 on 2023-02-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_post_email_alter_post_nom_de_la_mere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='COPIE_DU_PASSPORT',
        ),
        migrations.RemoveField(
            model_name='post',
            name='DATE_DE_NAISSANCE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='EMAIL',
        ),
    ]
