# Generated by Django 4.1.7 on 2023-02-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_post_copie_du_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='DIPLOMES',
        ),
        migrations.RemoveField(
            model_name='post',
            name='FACULTE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='LIEU_DE_NAISSANCE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='LOGEMENT',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NATIONALITE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NIVEAU_EN_ANGLAIS',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NOM_DE_LA_MERE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NOM_DU_PERE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='NUMERO_DE_TEL',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PHOTO',
        ),
        migrations.RemoveField(
            model_name='post',
            name='PROGRAMME',
        ),
        migrations.RemoveField(
            model_name='post',
            name='UNIVERSITE',
        ),
        migrations.DeleteModel(
            name='CAMPUS',
        ),
        migrations.DeleteModel(
            name='faculté',
        ),
        migrations.DeleteModel(
            name='NATIONALITE',
        ),
        migrations.DeleteModel(
            name='PROGRAMME',
        ),
        migrations.DeleteModel(
            name='UNIVERSITE',
        ),
    ]
