# Generated by Django 4.1.7 on 2023-03-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
