# Generated by Django 4.1.7 on 2023-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_nom_post_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='POSTNOM',
            field=models.CharField(default='', max_length=40),
        ),
    ]
