# Generated by Django 4.1.7 on 2023-02-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_campus_faculté_nationalite_programme_universite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='COPIE_DU_PASSPORT',
            field=models.FileField(default=' ', upload_to='USERS/DIPLOME/'),
        ),
        migrations.AddField(
            model_name='post',
            name='DIPLOME',
            field=models.FileField(default=' ', upload_to='USERS/DIPLOME/'),
        ),
        migrations.AddField(
            model_name='post',
            name='DIPLOMES',
            field=models.FileField(default=' ', upload_to='USERS/DIPLOME/'),
        ),
        migrations.AddField(
            model_name='post',
            name='NIVEAU_EN_ANGLAIS',
            field=models.FileField(default=' ', upload_to='USERS/NIVEAU/'),
        ),
        migrations.AddField(
            model_name='post',
            name='NOM_DE_LA_MERE',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='NOM_DU_PERE',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='PHOTO',
            field=models.ImageField(default=' ', upload_to='USERS/PHOTO_pics'),
        ),
    ]
