# Generated by Django 4.1.7 on 2023-03-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_departement_post_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='Departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.faculté'),
        ),
    ]
