# Generated by Django 4.1.7 on 2023-03-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_departement_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='date',
        ),
    ]
