# Generated by Django 4.1.7 on 2023-03-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_campus_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='COPIE_DU_PASSPORT',
            field=models.FileField(default=' ', upload_to='passport/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='DIPLOMES',
            field=models.FileField(default=' ', upload_to='DIPLOME/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='NIVEAU_EN_ANGLAIS',
            field=models.FileField(default=' ', upload_to='NIVEAU/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='PHOTO',
            field=models.ImageField(default=' ', upload_to='PHOTO_pics'),
        ),
    ]
